### PR TITLE
Add support for Python 3.11

### LINKED ISSUE #526: Support Python 3.11
## Description

Would it be possible to add support for Python 3.11? The [`pyproject.toml`](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/cellxgene_census/pyproject.toml#L14) currently states that this is blocked by numba, but it looks like [the newest version](https://numba.readthedocs.io/en/stable/release-notes.html) addresses this.

## Context

scvi-tools support for Python 3.11 is blocked by this as we depend on cellxgene-census.

## Impact

N/A

## Alternatives you've considered

N/A

## Ideal behavior 

N/A

### PR DESCRIPTION
**Pull request by martinkim0**
Closes #526

### CODE REVIEW

**Review by bkmartinjr — CHANGES_REQUESTED** [review]
This looks super - thanks for doing it.

One small change requested:  add 3.11 to the test matrix in `.github/workflows/py-unittests.yml`. Only needed for the job `unit_tests_python_api`.

One note: until TileDB-SOMA updates to the numba latest, we will be pinned to an RC (which does support 3.11).   See single-cell-data/TileDB-SOMA#1463

**Review by bkmartinjr — APPROVED** [review]
This LGTM.

**Review by atolopko-czi — APPROVED** [review]
LGTM (though I haven't personally tested a local `pip install -e` in a 3.11 env)

**Comment by bkmartinjr** [comment]
> LGTM (though I haven't personally tested a local pip install -e in a 3.11 env)

It passed the test matrix

**Pull request merged**
