### PR TITLE
Add integration vignette

### PR DESCRIPTION
**Pull request by pablo-gar**
partially addresses #248 

preview: https://rpubs.com/pablo-gar/1060914

### CODE REVIEW

**Comment by mlin** [comment]
@pablo-gar Hmm I swear I left a comment here earlier this week, evidently not sorry! I suspect the new vignette is using too much memory for the GitHub Actions worker (which has only 7GB RAM). Do you have any feel for what it uses locally?

We can either scale down the problem size in the vignette to use less memory, or forego building this one as part of the CI workflow. (I don't think we build the Python notebooks in CI, do we?) WDYT?

**Comment by mlin** [comment]
@pablo-gar just following up, is https://github.com/single-cell-data/TileDB-SOMA/pull/1274/files maybe going to be helpful for this?

**Review by mlin — APPROVED** [review]
I ran it locally, looks great! We'll need to move the file around depending which way we decide to go on #583, but we can handle that in either order easily.

**Comment by pablo-gar** [comment]
Merged via  #583

**Pull request closed without merging**
