### PR TITLE
Remove upperbound on numpy

### LINKED ISSUE #979: Support NumPy >= 1.25
The numpy dependency is currently upperbounded with `<1.25`, which is causing dependency issues when attempting to install scvi-tools and cellxgene-census in the same environment. I believe the newest numba releases support numpy 1.25, so would it be possible to increase the upperbound here? Thanks.

### PR DESCRIPTION
**Pull request by martinkim0**
Closes #979

### CODE REVIEW

**Review by bkmartinjr — APPROVED** [review]
LGTM.  Will continue to install old versions of numpy on Python 3.8 due to upstream pin (in tiledbsoma), but Python 3.9+ will get latest.

**Comment by bkmartinjr** [comment]
@martinkim0 - do you need this soon?  If so, we will need to drop a release containing the change.  Please let us know.

**Comment by martinkim0** [comment]
Great, thanks for approving @bkmartinjr! Not very urgent, but it would be nice to have as soon as possible. Is there a schedule for the next release?

**Comment by bkmartinjr** [comment]
> Is there a schedule

We do them as needed, and not on a regular schedule.  I'll raise the issue with the team and see if we can get it moving.

**Pull request merged**
