### PR TITLE
[r] add r-dependency-check.yml nightly test of current release package

### PR DESCRIPTION
**Pull request by mlin**
#751. Following #763, add an analogous nightly workflow for R to install the current release version of `cellxgene.census` then run the unit tests, to verify compatibility with the most up-to-date dependency versions.

The approach is simpler than #763 because R source packages include the unit test code, so we can just run them from the installed package directory.

### CODE REVIEW

**Comment by mlin** [comment]
@bkmartinjr @pablo-gar Just pending removal of the `pull_request:` trigger here.

**Review by bkmartinjr — APPROVED** [review]

**Review by pablo-gar — APPROVED** [review]

**Comment by bkmartinjr** [comment]
@mlin - any update on landing this?

**Comment by mlin** [comment]
@bkmartinjr I'd finished this diff at virtually the same hour that TileDB-R 0.21.0 was released, i.e. I went to merge it only to find it failing CI due to the precise problem it's designed to detect 💯 

So I thought it would be nice to see it passing again before merging, but I don't feel too strongly either way.

**Comment by mlin** [comment]
bump

**Comment by mlin** [comment]
Resuming testing of this with [tiledbsoma 1.5.0](https://tiledb-inc.r-universe.dev/builds)

**Pull request merged**
