### PR TITLE
[docs] Remove similarity search notebook

### PR DESCRIPTION
**Pull request by ebezzi**
This notebook isn't ready for the docsite yet.

### CODE REVIEW

**Review by ivirshup — CHANGES_REQUESTED** [review]
I think this would also need to be removed from `docs/examples.rst:30`

Would it make sense to just revert and reopen the PR that added this? It would also be good to make sure that re-adding this was tracked for the next release.

cc: @pablo-gar

**Comment by ebezzi** [comment]
> I think this would also need to be removed from `docs/examples.rst:30`
> 
> Would it make sense to just revert and reopen the PR that added this? It would also be good to make sure that re-adding this was tracked for the next release.
> 
> cc: @pablo-gar

Thanks, forgot about that.

I think it makes sense to keep the notebook if we don't link it in the docsite.

**Comment by ivirshup** [comment]
As discussed in person, we can probably do a doc build from this PR and not need to re-add things later.

**Comment by ebezzi** [comment]
Closing this - the branch was enough for patching the docsite.

**Pull request closed without merging**
